source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'
project 'XYDebugViewDemo.xcodeproj'

install! 'cocoapods',
  deterministic_uuids: false,
  warn_for_unused_master_specs_repo: false

target 'XYDebugViewDemo' do
  pod 'XYDebugView', path: '..'
end

post_install do |installer|
  deployment_target = '13.0'

  installer.generated_projects.each do |project|
    project.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
    end

    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
      end
    end

    project.save
  end

  installer.aggregate_targets
           .map(&:user_project)
           .uniq
           .each do |project|
    project.root_object.attributes['LastUpgradeCheck'] = '2620'

    project.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
    end

    project.native_targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
      end
    end

    project.save
  end
end
